version: "3"

services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    image: chat_backend
    container_name: chat_app
    env_file: .env
    volumes:
      - .:/app/
    ports:
      - 8000:8000

volumes: {}
