# Generated by Django 4.2 on 2023-04-12 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("thread", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="participants",
            field=models.ManyToManyField(related_name="threads", to=settings.AUTH_USER_MODEL),
        ),
    ]
