# Generated by Django 4.2 on 2023-04-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thread", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="header",
            field=models.CharField(default=None, max_length=128),
        ),
    ]
