# Generated by Django 4.2 on 2023-04-12 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("thread", "0003_thread_header"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="header",
        ),
    ]
